### ISSUE TITLE
config.toml file in the server does not reflect to UI

### ISSUE THREAD

**Issue by aj-super** [PrefectHQ/server#119]
# Description
Hello!
Please look at the attached screenshot. I am deploying the Prefect Server on the EC2 instance. I changed the address for server.ui.graphql_url in config.toml to reflect this. However this isn't reflected in UI, which keeps referring to localhost.

![image](https://user-images.githubusercontent.com/34548664/97425220-0a989200-18cf-11eb-891d-ac9d90325ded.png)

# Result
The localhost is changed to the ip adress

# Deployment Step I did
1. Used the following config.toml file:
```
[server]
host = "http://34.209.184.154"
port = "4200"
host_port = "4200"
endpoint = "${server.host}:${server.port}"

        [server.graphql]
        host = "34.209.184.154"

        [server.ui]
        host = "http://34.209.184.154"
        port = "8080"
        host_port = "8080"
        apollo_url = "http://34.209.184.154:4200/graphql"
```
2. docker system prune -a ( optional )
3. prefect server start
4. http://34.209.184.154:8080/

Could you please let me know what I'm missing? 
Looking forward to hearing from you!
Thanks.

_Originally posted by @aj-super in https://github.com/PrefectHQ/prefect/discussions/3580_

**Comment by znicholasbrown** [comment]
Hi @aj-super - which version of Prefect are you using? You mention setting 2 different variables, `apollo_url` and `graphql_url` - only `apollo_url` will work with the current version of Prefect. You can confirm that your variables were correctly applied by visiting: http://34.209.184.154:8080/settings.json, which will show which variable was populated by the container when it was started. Note: any changes you make to environment variables or your config.toml will require a restart of the UI container.

**Comment by aj-super** [comment]
- My version of Prefect is 0.13.12
- from visiting `http://34.209.184.154:8080/settings.json`, I can see that the server url has been changed correctly like in config.toml file:
{
  "server_url": "http://34.209.184.154:4200/graphql"
}

**Comment by znicholasbrown** [comment]
@aj-super I think your issue is should be resolved by https://github.com/PrefectHQ/ui/pull/360; would you mind upgrading to Prefect 0.13.13? That version of Core contains the fix.

**Comment by aj-super** [comment]
oh.. Can you please let me know where is the document to upgrade the version of Prefect?

**Comment by znicholasbrown** [comment]
Sure @aj-super - please see the docs on [single node deployment and upgrading Prefect Server](https://docs.prefect.io/orchestration/Server/deploy-local.html#how-to-upgrade-your-server-instance).

**Comment by aj-super** [comment]
I can still see the same issue.  What I did:
1. `docker system prune -a` ( to clean cache and stop everything )
2. `pip install prefect==0.13.13`
3. `prefect server start`

But I can still see that the prefect UI sends request to `localhost:4200` despite I use the config.toml file like so:
```
[server]
host = "http://34.209.184.154"
port = "4200"
host_port = "4200"
endpoint = "${server.host}:${server.port}"

        [server.graphql]
        host = "34.209.184.154"

        [server.ui]
        host = "http://34.209.184.154"
        port = "8080"
        host_port = "8080"
        apollo_url = "http://34.209.184.154:4200/graphql"
```

What am I missing?

**Comment by aj-super** [comment]
Ohhhhh,.... It works! After cleaning the cache on the browser, I can see that it works.
Thanks for your kind suggestion, @znicholasbrown

**Comment by znicholasbrown** [comment]
Great @aj-super ! Closing this issue.
